version: '3'
services:
        postgresdb:
                image: postgres:latest
                container_name: postgres-container
                environment:
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        POSTGRES_DB: ${POSTGRES_DB_NAME}
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                ports:
                        - "5432:5432"
                networks:
                        - postgres_network

        pgadmin:
                image: dpage/pgadmin4
                container_name: pgadmin
                environment:
                        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
                        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
                depends_on:
                        - postgresdb
                ports:
                        - "5050:80"
                networks:
                        - postgres_network

volumes:
        postgres_data:

networks:
        postgres_network:
                driver: bridge
